// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Error.proto

#include "proto/Error.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class ErrorResponseDefaultTypeInternal {
public:
    ::google::protobuf::internal::ExplicitlyConstructed <ErrorResponse>
            _instance;
} _ErrorResponse_default_instance_;
namespace protobuf_proto_2fError_2eproto {
    static void InitDefaultsErrorResponse() {
        GOOGLE_PROTOBUF_VERIFY_VERSION;

        {
            void *ptr = &::_ErrorResponse_default_instance_;
            new(ptr) ::ErrorResponse();
            ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
        }
        ::ErrorResponse::InitAsDefaultInstance();
    }

    ::google::protobuf::internal::SCCInfo <0> scc_info_ErrorResponse =
            {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsErrorResponse},
             {}};

    void InitDefaults() {
        ::google::protobuf::internal::InitSCC(&scc_info_ErrorResponse.base);
    }

    ::google::protobuf::Metadata file_level_metadata[1];

    const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
            ~0u,  // no _has_bits_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ErrorResponse, _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ErrorResponse, name_),
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ErrorResponse, message_),
    };
    static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
            {0, -1, sizeof(::ErrorResponse)},
    };

    static ::google::protobuf::Message const *const file_default_instances[] = {
            reinterpret_cast<const ::google::protobuf::Message *>(&::_ErrorResponse_default_instance_),
    };

    void protobuf_AssignDescriptors() {
        AddDescriptors();
        AssignDescriptors(
                "proto/Error.proto", schemas, file_default_instances, TableStruct::offsets,
                file_level_metadata, NULL, NULL);
    }

    void protobuf_AssignDescriptorsOnce() {
        static ::google::protobuf::internal::once_flag once;
        ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
    }

    void protobuf_RegisterTypes(const ::std::string &) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;

    void protobuf_RegisterTypes(const ::std::string &) {
        protobuf_AssignDescriptorsOnce();
        ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
    }

    void AddDescriptorsImpl() {
        InitDefaults();
        static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
                "\n\021proto/Error.proto\".\n\rErrorResponse\022\014\n\004"
                "name\030\001 \001(\t\022\017\n\007message\030\002 \001(\tB\034\n\016org.elec."
                "protoB\nErrorProtob\006proto3"
        };
        ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
                descriptor, 105);
        ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
                "proto/Error.proto", &protobuf_RegisterTypes);
    }

    void AddDescriptors() {
        static ::google::protobuf::internal::once_flag once;
        ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
    }

// Force AddDescriptors() to be called at dynamic initialization time.
    struct StaticDescriptorInitializer {
        StaticDescriptorInitializer() {
            AddDescriptors();
        }
    } static_descriptor_initializer;
}  // namespace protobuf_proto_2fError_2eproto

// ===================================================================

void ErrorResponse::InitAsDefaultInstance() {
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ErrorResponse::kNameFieldNumber;
const int ErrorResponse::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ErrorResponse::ErrorResponse()
        : ::google::protobuf::Message(), _internal_metadata_(NULL) {
    ::google::protobuf::internal::InitSCC(
            &protobuf_proto_2fError_2eproto::scc_info_ErrorResponse.base);
    SharedCtor();
    // @@protoc_insertion_point(constructor:ErrorResponse)
}

ErrorResponse::ErrorResponse(const ErrorResponse &from)
        : ::google::protobuf::Message(),
          _internal_metadata_(NULL) {
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    if (from.name().size() > 0) {
        name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    if (from.message().size() > 0) {
        message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
    }
    // @@protoc_insertion_point(copy_constructor:ErrorResponse)
}

void ErrorResponse::SharedCtor() {
    name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ErrorResponse::~ErrorResponse() {
    // @@protoc_insertion_point(destructor:ErrorResponse)
    SharedDtor();
}

void ErrorResponse::SharedDtor() {
    name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ErrorResponse::SetCachedSize(int size) const {
    _cached_size_.Set(size);
}

const ::google::protobuf::Descriptor *ErrorResponse::descriptor() {
    ::protobuf_proto_2fError_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_proto_2fError_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ErrorResponse &ErrorResponse::default_instance() {
    ::google::protobuf::internal::InitSCC(&protobuf_proto_2fError_2eproto::scc_info_ErrorResponse.base);
    return *internal_default_instance();
}


void ErrorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ErrorResponse)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void) cached_has_bits;

    name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    _internal_metadata_.Clear();
}

bool ErrorResponse::MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:ErrorResponse)
    for (;;) {
        ::std::pair <::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag = p.first;
        if (!p.second) goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
            // string name = 1;
            case 1: {
                if (static_cast< ::google::protobuf::uint8>(tag) ==
                    static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
                    DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                            input, this->mutable_name()));
                    DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                            this->name().data(), static_cast<int>(this->name().length()),
                            ::google::protobuf::internal::WireFormatLite::PARSE,
                            "ErrorResponse.name"));
                } else {
                    goto handle_unusual;
                }
                break;
            }

                // string message = 2;
            case 2: {
                if (static_cast< ::google::protobuf::uint8>(tag) ==
                    static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
                    DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                            input, this->mutable_message()));
                    DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                            this->message().data(), static_cast<int>(this->message().length()),
                            ::google::protobuf::internal::WireFormatLite::PARSE,
                            "ErrorResponse.message"));
                } else {
                    goto handle_unusual;
                }
                break;
            }

            default: {
                handle_unusual:
                if (tag == 0) {
                    goto success;
                }
                DO_(::google::protobuf::internal::WireFormat::SkipField(
                        input, tag, _internal_metadata_.mutable_unknown_fields()));
                break;
            }
        }
    }
    success:
    // @@protoc_insertion_point(parse_success:ErrorResponse)
    return true;
    failure:
    // @@protoc_insertion_point(parse_failure:ErrorResponse)
    return false;
#undef DO_
}

void ErrorResponse::SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const {
    // @@protoc_insertion_point(serialize_start:ErrorResponse)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void) cached_has_bits;

    // string name = 1;
    if (this->name().size() > 0) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                this->name().data(), static_cast<int>(this->name().length()),
                ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                "ErrorResponse.name");
        ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                1, this->name(), output);
    }

    // string message = 2;
    if (this->message().size() > 0) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                this->message().data(), static_cast<int>(this->message().length()),
                ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                "ErrorResponse.message");
        ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                2, this->message(), output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), output);
    }
    // @@protoc_insertion_point(serialize_end:ErrorResponse)
}

::google::protobuf::uint8 *ErrorResponse::InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const {
    (void) deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:ErrorResponse)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void) cached_has_bits;

    // string name = 1;
    if (this->name().size() > 0) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                this->name().data(), static_cast<int>(this->name().length()),
                ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                "ErrorResponse.name");
        target =
                ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                        1, this->name(), target);
    }

    // string message = 2;
    if (this->message().size() > 0) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                this->message().data(), static_cast<int>(this->message().length()),
                ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                "ErrorResponse.message");
        target =
                ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                        2, this->message(), target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:ErrorResponse)
    return target;
}

size_t ErrorResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ErrorResponse)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
        total_size +=
                ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()));
    }
    // string name = 1;
    if (this->name().size() > 0) {
        total_size += 1 +
                      ::google::protobuf::internal::WireFormatLite::StringSize(
                              this->name());
    }

    // string message = 2;
    if (this->message().size() > 0) {
        total_size += 1 +
                      ::google::protobuf::internal::WireFormatLite::StringSize(
                              this->message());
    }

    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    SetCachedSize(cached_size);
    return total_size;
}

void ErrorResponse::MergeFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_merge_from_start:ErrorResponse)
            GOOGLE_DCHECK_NE(&from, this);
    const ErrorResponse *source =
            ::google::protobuf::internal::DynamicCastToGenerated <const ErrorResponse>(
                    &from);
    if (source == NULL) {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:ErrorResponse)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    } else {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:ErrorResponse)
        MergeFrom(*source);
    }
}

void ErrorResponse::MergeFrom(const ErrorResponse &from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ErrorResponse)
            GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void) cached_has_bits;

    if (from.name().size() > 0) {

        name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (from.message().size() > 0) {

        message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
    }
}

void ErrorResponse::CopyFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_copy_from_start:ErrorResponse)
    if (&from == this) return;
    Clear();
    MergeFrom(from);
}

void ErrorResponse::CopyFrom(const ErrorResponse &from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ErrorResponse)
    if (&from == this) return;
    Clear();
    MergeFrom(from);
}

bool ErrorResponse::IsInitialized() const {
    return true;
}

void ErrorResponse::Swap(ErrorResponse *other) {
    if (other == this) return;
    InternalSwap(other);
}

void ErrorResponse::InternalSwap(ErrorResponse *other) {
    using std::swap;
    name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
               GetArenaNoVirtual());
    message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                  GetArenaNoVirtual());
    _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ErrorResponse::GetMetadata() const {
    protobuf_proto_2fError_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_proto_2fError_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
    namespace protobuf {
        template <>
        GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ErrorResponse *Arena::CreateMaybeMessage <::ErrorResponse>(Arena *arena) {
            return Arena::CreateInternal <::ErrorResponse>(arena);
        }
    }  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
