// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Security.proto

#include "Security.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace proto {
    class ClientHelloDefaultTypeInternal {
    public:
        ::google::protobuf::internal::ExplicitlyConstructed <ClientHello>
                _instance;
    } _ClientHello_default_instance_;

    class ServerHelloDefaultTypeInternal {
    public:
        ::google::protobuf::internal::ExplicitlyConstructed <ServerHello>
                _instance;
    } _ServerHello_default_instance_;

    class ClientSecurityDefaultTypeInternal {
    public:
        ::google::protobuf::internal::ExplicitlyConstructed <ClientSecurity>
                _instance;
    } _ClientSecurity_default_instance_;

    class ClientSecurityResponseDefaultTypeInternal {
    public:
        ::google::protobuf::internal::ExplicitlyConstructed <ClientSecurityResponse>
                _instance;
    } _ClientSecurityResponse_default_instance_;
}  // namespace proto
namespace protobuf_proto_2fSecurity_2eproto {
    static void InitDefaultsClientHello() {
        GOOGLE_PROTOBUF_VERIFY_VERSION;

        {
            void *ptr = &::proto::_ClientHello_default_instance_;
            new(ptr) ::proto::ClientHello();
            ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
        }
        ::proto::ClientHello::InitAsDefaultInstance();
    }

    ::google::protobuf::internal::SCCInfo <0> scc_info_ClientHello =
            {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClientHello},
             {}};

    static void InitDefaultsServerHello() {
        GOOGLE_PROTOBUF_VERIFY_VERSION;

        {
            void *ptr = &::proto::_ServerHello_default_instance_;
            new(ptr) ::proto::ServerHello();
            ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
        }
        ::proto::ServerHello::InitAsDefaultInstance();
    }

    ::google::protobuf::internal::SCCInfo <0> scc_info_ServerHello =
            {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsServerHello},
             {}};

    static void InitDefaultsClientSecurity() {
        GOOGLE_PROTOBUF_VERIFY_VERSION;

        {
            void *ptr = &::proto::_ClientSecurity_default_instance_;
            new(ptr) ::proto::ClientSecurity();
            ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
        }
        ::proto::ClientSecurity::InitAsDefaultInstance();
    }

    ::google::protobuf::internal::SCCInfo <0> scc_info_ClientSecurity =
            {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClientSecurity},
             {}};

    static void InitDefaultsClientSecurityResponse() {
        GOOGLE_PROTOBUF_VERIFY_VERSION;

        {
            void *ptr = &::proto::_ClientSecurityResponse_default_instance_;
            new(ptr) ::proto::ClientSecurityResponse();
            ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
        }
        ::proto::ClientSecurityResponse::InitAsDefaultInstance();
    }

    ::google::protobuf::internal::SCCInfo <0> scc_info_ClientSecurityResponse =
            {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClientSecurityResponse},
             {}};

    void InitDefaults() {
        ::google::protobuf::internal::InitSCC(&scc_info_ClientHello.base);
        ::google::protobuf::internal::InitSCC(&scc_info_ServerHello.base);
        ::google::protobuf::internal::InitSCC(&scc_info_ClientSecurity.base);
        ::google::protobuf::internal::InitSCC(&scc_info_ClientSecurityResponse.base);
    }

    ::google::protobuf::Metadata file_level_metadata[4];

    const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
            ~0u,  // no _has_bits_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientHello, _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientHello, version_),
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientHello, clientrandom_),
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientHello, sessionid_),
            ~0u,  // no _has_bits_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ServerHello, _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ServerHello, version_),
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ServerHello, serverrandom_),
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ServerHello, sessionid_),
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ServerHello, certificate_),
            ~0u,  // no _has_bits_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientSecurity, _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientSecurity, pre_master_secret_),
            ~0u,  // no _has_bits_
            GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ClientSecurityResponse, _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
    };
    static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
            {0,  -1, sizeof(::proto::ClientHello)},
            {8,  -1, sizeof(::proto::ServerHello)},
            {17, -1, sizeof(::proto::ClientSecurity)},
            {23, -1, sizeof(::proto::ClientSecurityResponse)},
    };

    static ::google::protobuf::Message const *const file_default_instances[] = {
            reinterpret_cast<const ::google::protobuf::Message *>(&::proto::_ClientHello_default_instance_),
            reinterpret_cast<const ::google::protobuf::Message *>(&::proto::_ServerHello_default_instance_),
            reinterpret_cast<const ::google::protobuf::Message *>(&::proto::_ClientSecurity_default_instance_),
            reinterpret_cast<const ::google::protobuf::Message *>(&::proto::_ClientSecurityResponse_default_instance_),
    };

    void protobuf_AssignDescriptors() {
        AddDescriptors();
        AssignDescriptors(
                "proto/Security.proto", schemas, file_default_instances, TableStruct::offsets,
                file_level_metadata, NULL, NULL);
    }

    void protobuf_AssignDescriptorsOnce() {
        static ::google::protobuf::internal::once_flag once;
        ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
    }

    void protobuf_RegisterTypes(const ::std::string &) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;

    void protobuf_RegisterTypes(const ::std::string &) {
        protobuf_AssignDescriptorsOnce();
        ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
    }

    void AddDescriptorsImpl() {
        InitDefaults();
        static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
                "\n\024proto/Security.proto\022\005proto\"G\n\013ClientH"
                "ello\022\017\n\007version\030\001 \001(\t\022\024\n\014clientRandom\030\002 "
                "\001(\t\022\021\n\tsessionId\030\003 \001(\t\"\\\n\013ServerHello\022\017\n"
                "\007version\030\001 \001(\t\022\024\n\014serverRandom\030\002 \001(\t\022\021\n\t"
                "sessionId\030\003 \001(\t\022\023\n\013certificate\030\004 \001(\014\"+\n\016"
                "ClientSecurity\022\031\n\021pre_master_secret\030\001 \001("
                "\014\"\030\n\026ClientSecurityResponseB\037\n\016org.elec."
                "protoB\rSecurityProtob\006proto3"
        };
        ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
                descriptor, 308);
        ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
                "proto/Security.proto", &protobuf_RegisterTypes);
    }

    void AddDescriptors() {
        static ::google::protobuf::internal::once_flag once;
        ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
    }

// Force AddDescriptors() to be called at dynamic initialization time.
    struct StaticDescriptorInitializer {
        StaticDescriptorInitializer() {
            AddDescriptors();
        }
    } static_descriptor_initializer;
}  // namespace protobuf_proto_2fSecurity_2eproto
namespace proto {

// ===================================================================

    void ClientHello::InitAsDefaultInstance() {
    }

#if !defined(_MSC_VER) || _MSC_VER >= 1900
    const int ClientHello::kVersionFieldNumber;
    const int ClientHello::kClientRandomFieldNumber;
    const int ClientHello::kSessionIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

    ClientHello::ClientHello()
            : ::google::protobuf::Message(), _internal_metadata_(NULL) {
        ::google::protobuf::internal::InitSCC(
                &protobuf_proto_2fSecurity_2eproto::scc_info_ClientHello.base);
        SharedCtor();
        // @@protoc_insertion_point(constructor:proto.ClientHello)
    }

    ClientHello::ClientHello(const ClientHello &from)
            : ::google::protobuf::Message(),
              _internal_metadata_(NULL) {
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.version().size() > 0) {
            version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
        }
        clientrandom_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.clientrandom().size() > 0) {
            clientrandom_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientrandom_);
        }
        sessionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.sessionid().size() > 0) {
            sessionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionid_);
        }
        // @@protoc_insertion_point(copy_constructor:proto.ClientHello)
    }

    void ClientHello::SharedCtor() {
        version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        clientrandom_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        sessionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }

    ClientHello::~ClientHello() {
        // @@protoc_insertion_point(destructor:proto.ClientHello)
        SharedDtor();
    }

    void ClientHello::SharedDtor() {
        version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        clientrandom_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        sessionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }

    void ClientHello::SetCachedSize(int size) const {
        _cached_size_.Set(size);
    }

    const ::google::protobuf::Descriptor *ClientHello::descriptor() {
        ::protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
    }

    const ClientHello &ClientHello::default_instance() {
        ::google::protobuf::internal::InitSCC(&protobuf_proto_2fSecurity_2eproto::scc_info_ClientHello.base);
        return *internal_default_instance();
    }


    void ClientHello::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ClientHello)
        ::google::protobuf::uint32 cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        clientrandom_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        sessionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        _internal_metadata_.Clear();
    }

    bool ClientHello::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:proto.ClientHello)
        for (;;) {
            ::std::pair <::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
                // string version = 1;
                case 1: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_version()));
                        DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                                this->version().data(), static_cast<int>(this->version().length()),
                                ::google::protobuf::internal::WireFormatLite::PARSE,
                                "proto.ClientHello.version"));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                    // string clientRandom = 2;
                case 2: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_clientrandom()));
                        DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                                this->clientrandom().data(), static_cast<int>(this->clientrandom().length()),
                                ::google::protobuf::internal::WireFormatLite::PARSE,
                                "proto.ClientHello.clientRandom"));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                    // string sessionId = 3;
                case 3: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_sessionid()));
                        DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                                this->sessionid().data(), static_cast<int>(this->sessionid().length()),
                                ::google::protobuf::internal::WireFormatLite::PARSE,
                                "proto.ClientHello.sessionId"));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                default: {
                    handle_unusual:
                    if (tag == 0) {
                        goto success;
                    }
                    DO_(::google::protobuf::internal::WireFormat::SkipField(
                            input, tag, _internal_metadata_.mutable_unknown_fields()));
                    break;
                }
            }
        }
        success:
        // @@protoc_insertion_point(parse_success:proto.ClientHello)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:proto.ClientHello)
        return false;
#undef DO_
    }

    void ClientHello::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:proto.ClientHello)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        // string version = 1;
        if (this->version().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->version().data(), static_cast<int>(this->version().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ClientHello.version");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    1, this->version(), output);
        }

        // string clientRandom = 2;
        if (this->clientrandom().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->clientrandom().data(), static_cast<int>(this->clientrandom().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ClientHello.clientRandom");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    2, this->clientrandom(), output);
        }

        // string sessionId = 3;
        if (this->sessionid().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->sessionid().data(), static_cast<int>(this->sessionid().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ClientHello.sessionId");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    3, this->sessionid(), output);
        }

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), output);
        }
        // @@protoc_insertion_point(serialize_end:proto.ClientHello)
    }

    ::google::protobuf::uint8 *ClientHello::InternalSerializeWithCachedSizesToArray(
            bool deterministic, ::google::protobuf::uint8 *target) const {
        (void) deterministic; // Unused
        // @@protoc_insertion_point(serialize_to_array_start:proto.ClientHello)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        // string version = 1;
        if (this->version().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->version().data(), static_cast<int>(this->version().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ClientHello.version");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            1, this->version(), target);
        }

        // string clientRandom = 2;
        if (this->clientrandom().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->clientrandom().data(), static_cast<int>(this->clientrandom().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ClientHello.clientRandom");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            2, this->clientrandom(), target);
        }

        // string sessionId = 3;
        if (this->sessionid().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->sessionid().data(), static_cast<int>(this->sessionid().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ClientHello.sessionId");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            3, this->sessionid(), target);
        }

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:proto.ClientHello)
        return target;
    }

    size_t ClientHello::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ClientHello)
        size_t total_size = 0;

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()));
        }
        // string version = 1;
        if (this->version().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->version());
        }

        // string clientRandom = 2;
        if (this->clientrandom().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->clientrandom());
        }

        // string sessionId = 3;
        if (this->sessionid().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->sessionid());
        }

        int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
        SetCachedSize(cached_size);
        return total_size;
    }

    void ClientHello::MergeFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.ClientHello)
                GOOGLE_DCHECK_NE(&from, this);
        const ClientHello *source =
                ::google::protobuf::internal::DynamicCastToGenerated <const ClientHello>(
                        &from);
        if (source == NULL) {
            // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.ClientHello)
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.ClientHello)
            MergeFrom(*source);
        }
    }

    void ClientHello::MergeFrom(const ClientHello &from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ClientHello)
                GOOGLE_DCHECK_NE(&from, this);
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        if (from.version().size() > 0) {

            version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
        }
        if (from.clientrandom().size() > 0) {

            clientrandom_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientrandom_);
        }
        if (from.sessionid().size() > 0) {

            sessionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionid_);
        }
    }

    void ClientHello::CopyFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.ClientHello)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void ClientHello::CopyFrom(const ClientHello &from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ClientHello)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool ClientHello::IsInitialized() const {
        return true;
    }

    void ClientHello::Swap(ClientHello *other) {
        if (other == this) return;
        InternalSwap(other);
    }

    void ClientHello::InternalSwap(ClientHello *other) {
        using std::swap;
        version_.Swap(&other->version_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                      GetArenaNoVirtual());
        clientrandom_.Swap(&other->clientrandom_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                           GetArenaNoVirtual());
        sessionid_.Swap(&other->sessionid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                        GetArenaNoVirtual());
        _internal_metadata_.Swap(&other->_internal_metadata_);
    }

    ::google::protobuf::Metadata ClientHello::GetMetadata() const {
        protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages];
    }


// ===================================================================

    void ServerHello::InitAsDefaultInstance() {
    }

#if !defined(_MSC_VER) || _MSC_VER >= 1900
    const int ServerHello::kVersionFieldNumber;
    const int ServerHello::kServerRandomFieldNumber;
    const int ServerHello::kSessionIdFieldNumber;
    const int ServerHello::kCertificateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

    ServerHello::ServerHello()
            : ::google::protobuf::Message(), _internal_metadata_(NULL) {
        ::google::protobuf::internal::InitSCC(
                &protobuf_proto_2fSecurity_2eproto::scc_info_ServerHello.base);
        SharedCtor();
        // @@protoc_insertion_point(constructor:proto.ServerHello)
    }

    ServerHello::ServerHello(const ServerHello &from)
            : ::google::protobuf::Message(),
              _internal_metadata_(NULL) {
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.version().size() > 0) {
            version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
        }
        serverrandom_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.serverrandom().size() > 0) {
            serverrandom_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.serverrandom_);
        }
        sessionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.sessionid().size() > 0) {
            sessionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionid_);
        }
        certificate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.certificate().size() > 0) {
            certificate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.certificate_);
        }
        // @@protoc_insertion_point(copy_constructor:proto.ServerHello)
    }

    void ServerHello::SharedCtor() {
        version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        serverrandom_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        sessionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        certificate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }

    ServerHello::~ServerHello() {
        // @@protoc_insertion_point(destructor:proto.ServerHello)
        SharedDtor();
    }

    void ServerHello::SharedDtor() {
        version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        serverrandom_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        sessionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        certificate_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }

    void ServerHello::SetCachedSize(int size) const {
        _cached_size_.Set(size);
    }

    const ::google::protobuf::Descriptor *ServerHello::descriptor() {
        ::protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
    }

    const ServerHello &ServerHello::default_instance() {
        ::google::protobuf::internal::InitSCC(&protobuf_proto_2fSecurity_2eproto::scc_info_ServerHello.base);
        return *internal_default_instance();
    }


    void ServerHello::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ServerHello)
        ::google::protobuf::uint32 cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        serverrandom_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        sessionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        certificate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        _internal_metadata_.Clear();
    }

    bool ServerHello::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:proto.ServerHello)
        for (;;) {
            ::std::pair <::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
                // string version = 1;
                case 1: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_version()));
                        DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                                this->version().data(), static_cast<int>(this->version().length()),
                                ::google::protobuf::internal::WireFormatLite::PARSE,
                                "proto.ServerHello.version"));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                    // string serverRandom = 2;
                case 2: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_serverrandom()));
                        DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                                this->serverrandom().data(), static_cast<int>(this->serverrandom().length()),
                                ::google::protobuf::internal::WireFormatLite::PARSE,
                                "proto.ServerHello.serverRandom"));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                    // string sessionId = 3;
                case 3: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_sessionid()));
                        DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                                this->sessionid().data(), static_cast<int>(this->sessionid().length()),
                                ::google::protobuf::internal::WireFormatLite::PARSE,
                                "proto.ServerHello.sessionId"));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                    // bytes certificate = 4;
                case 4: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                                input, this->mutable_certificate()));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                default: {
                    handle_unusual:
                    if (tag == 0) {
                        goto success;
                    }
                    DO_(::google::protobuf::internal::WireFormat::SkipField(
                            input, tag, _internal_metadata_.mutable_unknown_fields()));
                    break;
                }
            }
        }
        success:
        // @@protoc_insertion_point(parse_success:proto.ServerHello)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:proto.ServerHello)
        return false;
#undef DO_
    }

    void ServerHello::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:proto.ServerHello)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        // string version = 1;
        if (this->version().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->version().data(), static_cast<int>(this->version().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ServerHello.version");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    1, this->version(), output);
        }

        // string serverRandom = 2;
        if (this->serverrandom().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->serverrandom().data(), static_cast<int>(this->serverrandom().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ServerHello.serverRandom");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    2, this->serverrandom(), output);
        }

        // string sessionId = 3;
        if (this->sessionid().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->sessionid().data(), static_cast<int>(this->sessionid().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ServerHello.sessionId");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    3, this->sessionid(), output);
        }

        // bytes certificate = 4;
        if (this->certificate().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
                    4, this->certificate(), output);
        }

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), output);
        }
        // @@protoc_insertion_point(serialize_end:proto.ServerHello)
    }

    ::google::protobuf::uint8 *ServerHello::InternalSerializeWithCachedSizesToArray(
            bool deterministic, ::google::protobuf::uint8 *target) const {
        (void) deterministic; // Unused
        // @@protoc_insertion_point(serialize_to_array_start:proto.ServerHello)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        // string version = 1;
        if (this->version().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->version().data(), static_cast<int>(this->version().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ServerHello.version");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            1, this->version(), target);
        }

        // string serverRandom = 2;
        if (this->serverrandom().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->serverrandom().data(), static_cast<int>(this->serverrandom().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ServerHello.serverRandom");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            2, this->serverrandom(), target);
        }

        // string sessionId = 3;
        if (this->sessionid().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    this->sessionid().data(), static_cast<int>(this->sessionid().length()),
                    ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                    "proto.ServerHello.sessionId");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            3, this->sessionid(), target);
        }

        // bytes certificate = 4;
        if (this->certificate().size() > 0) {
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
                            4, this->certificate(), target);
        }

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:proto.ServerHello)
        return target;
    }

    size_t ServerHello::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ServerHello)
        size_t total_size = 0;

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()));
        }
        // string version = 1;
        if (this->version().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->version());
        }

        // string serverRandom = 2;
        if (this->serverrandom().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->serverrandom());
        }

        // string sessionId = 3;
        if (this->sessionid().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->sessionid());
        }

        // bytes certificate = 4;
        if (this->certificate().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::BytesSize(
                                  this->certificate());
        }

        int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
        SetCachedSize(cached_size);
        return total_size;
    }

    void ServerHello::MergeFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.ServerHello)
                GOOGLE_DCHECK_NE(&from, this);
        const ServerHello *source =
                ::google::protobuf::internal::DynamicCastToGenerated <const ServerHello>(
                        &from);
        if (source == NULL) {
            // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.ServerHello)
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.ServerHello)
            MergeFrom(*source);
        }
    }

    void ServerHello::MergeFrom(const ServerHello &from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ServerHello)
                GOOGLE_DCHECK_NE(&from, this);
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        if (from.version().size() > 0) {

            version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
        }
        if (from.serverrandom().size() > 0) {

            serverrandom_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.serverrandom_);
        }
        if (from.sessionid().size() > 0) {

            sessionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionid_);
        }
        if (from.certificate().size() > 0) {

            certificate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.certificate_);
        }
    }

    void ServerHello::CopyFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.ServerHello)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void ServerHello::CopyFrom(const ServerHello &from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ServerHello)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool ServerHello::IsInitialized() const {
        return true;
    }

    void ServerHello::Swap(ServerHello *other) {
        if (other == this) return;
        InternalSwap(other);
    }

    void ServerHello::InternalSwap(ServerHello *other) {
        using std::swap;
        version_.Swap(&other->version_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                      GetArenaNoVirtual());
        serverrandom_.Swap(&other->serverrandom_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                           GetArenaNoVirtual());
        sessionid_.Swap(&other->sessionid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                        GetArenaNoVirtual());
        certificate_.Swap(&other->certificate_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                          GetArenaNoVirtual());
        _internal_metadata_.Swap(&other->_internal_metadata_);
    }

    ::google::protobuf::Metadata ServerHello::GetMetadata() const {
        protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages];
    }


// ===================================================================

    void ClientSecurity::InitAsDefaultInstance() {
    }

#if !defined(_MSC_VER) || _MSC_VER >= 1900
    const int ClientSecurity::kPreMasterSecretFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

    ClientSecurity::ClientSecurity()
            : ::google::protobuf::Message(), _internal_metadata_(NULL) {
        ::google::protobuf::internal::InitSCC(
                &protobuf_proto_2fSecurity_2eproto::scc_info_ClientSecurity.base);
        SharedCtor();
        // @@protoc_insertion_point(constructor:proto.ClientSecurity)
    }

    ClientSecurity::ClientSecurity(const ClientSecurity &from)
            : ::google::protobuf::Message(),
              _internal_metadata_(NULL) {
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        pre_master_secret_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        if (from.pre_master_secret().size() > 0) {
            pre_master_secret_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pre_master_secret_);
        }
        // @@protoc_insertion_point(copy_constructor:proto.ClientSecurity)
    }

    void ClientSecurity::SharedCtor() {
        pre_master_secret_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }

    ClientSecurity::~ClientSecurity() {
        // @@protoc_insertion_point(destructor:proto.ClientSecurity)
        SharedDtor();
    }

    void ClientSecurity::SharedDtor() {
        pre_master_secret_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }

    void ClientSecurity::SetCachedSize(int size) const {
        _cached_size_.Set(size);
    }

    const ::google::protobuf::Descriptor *ClientSecurity::descriptor() {
        ::protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
    }

    const ClientSecurity &ClientSecurity::default_instance() {
        ::google::protobuf::internal::InitSCC(&protobuf_proto_2fSecurity_2eproto::scc_info_ClientSecurity.base);
        return *internal_default_instance();
    }


    void ClientSecurity::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ClientSecurity)
        ::google::protobuf::uint32 cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        pre_master_secret_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        _internal_metadata_.Clear();
    }

    bool ClientSecurity::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:proto.ClientSecurity)
        for (;;) {
            ::std::pair <::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
                // bytes pre_master_secret = 1;
                case 1: {
                    if (static_cast< ::google::protobuf::uint8>(tag) ==
                        static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                                input, this->mutable_pre_master_secret()));
                    } else {
                        goto handle_unusual;
                    }
                    break;
                }

                default: {
                    handle_unusual:
                    if (tag == 0) {
                        goto success;
                    }
                    DO_(::google::protobuf::internal::WireFormat::SkipField(
                            input, tag, _internal_metadata_.mutable_unknown_fields()));
                    break;
                }
            }
        }
        success:
        // @@protoc_insertion_point(parse_success:proto.ClientSecurity)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:proto.ClientSecurity)
        return false;
#undef DO_
    }

    void ClientSecurity::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:proto.ClientSecurity)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        // bytes pre_master_secret = 1;
        if (this->pre_master_secret().size() > 0) {
            ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
                    1, this->pre_master_secret(), output);
        }

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), output);
        }
        // @@protoc_insertion_point(serialize_end:proto.ClientSecurity)
    }

    ::google::protobuf::uint8 *ClientSecurity::InternalSerializeWithCachedSizesToArray(
            bool deterministic, ::google::protobuf::uint8 *target) const {
        (void) deterministic; // Unused
        // @@protoc_insertion_point(serialize_to_array_start:proto.ClientSecurity)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        // bytes pre_master_secret = 1;
        if (this->pre_master_secret().size() > 0) {
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
                            1, this->pre_master_secret(), target);
        }

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:proto.ClientSecurity)
        return target;
    }

    size_t ClientSecurity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ClientSecurity)
        size_t total_size = 0;

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()));
        }
        // bytes pre_master_secret = 1;
        if (this->pre_master_secret().size() > 0) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::BytesSize(
                                  this->pre_master_secret());
        }

        int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
        SetCachedSize(cached_size);
        return total_size;
    }

    void ClientSecurity::MergeFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.ClientSecurity)
                GOOGLE_DCHECK_NE(&from, this);
        const ClientSecurity *source =
                ::google::protobuf::internal::DynamicCastToGenerated <const ClientSecurity>(
                        &from);
        if (source == NULL) {
            // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.ClientSecurity)
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.ClientSecurity)
            MergeFrom(*source);
        }
    }

    void ClientSecurity::MergeFrom(const ClientSecurity &from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ClientSecurity)
                GOOGLE_DCHECK_NE(&from, this);
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        if (from.pre_master_secret().size() > 0) {

            pre_master_secret_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pre_master_secret_);
        }
    }

    void ClientSecurity::CopyFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.ClientSecurity)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void ClientSecurity::CopyFrom(const ClientSecurity &from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ClientSecurity)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool ClientSecurity::IsInitialized() const {
        return true;
    }

    void ClientSecurity::Swap(ClientSecurity *other) {
        if (other == this) return;
        InternalSwap(other);
    }

    void ClientSecurity::InternalSwap(ClientSecurity *other) {
        using std::swap;
        pre_master_secret_.Swap(&other->pre_master_secret_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                                GetArenaNoVirtual());
        _internal_metadata_.Swap(&other->_internal_metadata_);
    }

    ::google::protobuf::Metadata ClientSecurity::GetMetadata() const {
        protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages];
    }


// ===================================================================

    void ClientSecurityResponse::InitAsDefaultInstance() {
    }

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

    ClientSecurityResponse::ClientSecurityResponse()
            : ::google::protobuf::Message(), _internal_metadata_(NULL) {
        ::google::protobuf::internal::InitSCC(
                &protobuf_proto_2fSecurity_2eproto::scc_info_ClientSecurityResponse.base);
        SharedCtor();
        // @@protoc_insertion_point(constructor:proto.ClientSecurityResponse)
    }

    ClientSecurityResponse::ClientSecurityResponse(const ClientSecurityResponse &from)
            : ::google::protobuf::Message(),
              _internal_metadata_(NULL) {
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        // @@protoc_insertion_point(copy_constructor:proto.ClientSecurityResponse)
    }

    void ClientSecurityResponse::SharedCtor() {
    }

    ClientSecurityResponse::~ClientSecurityResponse() {
        // @@protoc_insertion_point(destructor:proto.ClientSecurityResponse)
        SharedDtor();
    }

    void ClientSecurityResponse::SharedDtor() {
    }

    void ClientSecurityResponse::SetCachedSize(int size) const {
        _cached_size_.Set(size);
    }

    const ::google::protobuf::Descriptor *ClientSecurityResponse::descriptor() {
        ::protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
    }

    const ClientSecurityResponse &ClientSecurityResponse::default_instance() {
        ::google::protobuf::internal::InitSCC(&protobuf_proto_2fSecurity_2eproto::scc_info_ClientSecurityResponse.base);
        return *internal_default_instance();
    }


    void ClientSecurityResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ClientSecurityResponse)
        ::google::protobuf::uint32 cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        _internal_metadata_.Clear();
    }

    bool ClientSecurityResponse::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:proto.ClientSecurityResponse)
        for (;;) {
            ::std::pair <::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            handle_unusual:
            if (tag == 0) {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(
                    input, tag, _internal_metadata_.mutable_unknown_fields()));
        }
        success:
        // @@protoc_insertion_point(parse_success:proto.ClientSecurityResponse)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:proto.ClientSecurityResponse)
        return false;
#undef DO_
    }

    void ClientSecurityResponse::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:proto.ClientSecurityResponse)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), output);
        }
        // @@protoc_insertion_point(serialize_end:proto.ClientSecurityResponse)
    }

    ::google::protobuf::uint8 *ClientSecurityResponse::InternalSerializeWithCachedSizesToArray(
            bool deterministic, ::google::protobuf::uint8 *target) const {
        (void) deterministic; // Unused
        // @@protoc_insertion_point(serialize_to_array_start:proto.ClientSecurityResponse)
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:proto.ClientSecurityResponse)
        return target;
    }

    size_t ClientSecurityResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ClientSecurityResponse)
        size_t total_size = 0;

        if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields() : _internal_metadata_.default_instance()));
        }
        int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
        SetCachedSize(cached_size);
        return total_size;
    }

    void ClientSecurityResponse::MergeFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.ClientSecurityResponse)
                GOOGLE_DCHECK_NE(&from, this);
        const ClientSecurityResponse *source =
                ::google::protobuf::internal::DynamicCastToGenerated <const ClientSecurityResponse>(
                        &from);
        if (source == NULL) {
            // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.ClientSecurityResponse)
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.ClientSecurityResponse)
            MergeFrom(*source);
        }
    }

    void ClientSecurityResponse::MergeFrom(const ClientSecurityResponse &from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ClientSecurityResponse)
                GOOGLE_DCHECK_NE(&from, this);
        _internal_metadata_.MergeFrom(from._internal_metadata_);
        ::google::protobuf::uint32 cached_has_bits = 0;
        (void) cached_has_bits;

    }

    void ClientSecurityResponse::CopyFrom(const ::google::protobuf::Message &from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.ClientSecurityResponse)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void ClientSecurityResponse::CopyFrom(const ClientSecurityResponse &from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ClientSecurityResponse)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool ClientSecurityResponse::IsInitialized() const {
        return true;
    }

    void ClientSecurityResponse::Swap(ClientSecurityResponse *other) {
        if (other == this) return;
        InternalSwap(other);
    }

    void ClientSecurityResponse::InternalSwap(ClientSecurityResponse *other) {
        using std::swap;
        _internal_metadata_.Swap(&other->_internal_metadata_);
    }

    ::google::protobuf::Metadata ClientSecurityResponse::GetMetadata() const {
        protobuf_proto_2fSecurity_2eproto::protobuf_AssignDescriptorsOnce();
        return ::protobuf_proto_2fSecurity_2eproto::file_level_metadata[kIndexInFileMessages];
    }


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
    namespace protobuf {
        template <>
        GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::ClientHello *Arena::CreateMaybeMessage <::proto::ClientHello>(Arena *arena) {
            return Arena::CreateInternal <::proto::ClientHello>(arena);
        }

        template <>
        GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::ServerHello *Arena::CreateMaybeMessage <::proto::ServerHello>(Arena *arena) {
            return Arena::CreateInternal <::proto::ServerHello>(arena);
        }

        template <>
        GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::ClientSecurity *Arena::CreateMaybeMessage <::proto::ClientSecurity>(Arena *arena) {
            return Arena::CreateInternal <::proto::ClientSecurity>(arena);
        }

        template <>
        GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::ClientSecurityResponse *Arena::CreateMaybeMessage <::proto::ClientSecurityResponse>(Arena *arena) {
            return Arena::CreateInternal <::proto::ClientSecurityResponse>(arena);
        }
    }  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
